const COUNTRY_PHONE_CODES = [
    { flag: "🇦🇫", value: "+93", label: "Afghanistan" },
    { flag: "🇦🇱", value: "+355", label: "Albania" },
    { flag: "🇩🇿", value: "+213", label: "Algeria" },
    { flag: "🇦🇸", value: "+1-684", label: "American Samoa" },
    { flag: "🇦🇩", value: "+376", label: "Andorra" },
    { flag: "🇦🇴", value: "+244", label: "Angola" },
    { flag: "🇦🇮", value: "+1-264", label: "Anguilla" },
    { flag: "🇦🇶", value: "+672", label: "Antarctica" },
    { flag: "🇦🇬", value: "+1-268", label: "Antigua and Barbuda" },
    { flag: "🇦🇷", value: "+54", label: "Argentina" },
    { flag: "🇦🇲", value: "+374", label: "Armenia" },
    { flag: "🇦🇼", value: "+297", label: "Aruba" },
    { flag: "🇦🇺", value: "+61", label: "Australia" },
    { flag: "🇦🇹", value: "+43", label: "Austria" },
    { flag: "🇦🇿", value: "+994", label: "Azerbaijan" },
    { flag: "🇧🇸", value: "+1-242", label: "Bahamas" },
    { flag: "🇧🇭", value: "+973", label: "Bahrain" },
    { flag: "🇧🇩", value: "+880", label: "Bangladesh" },
    { flag: "🇧🇧", value: "+1-246", label: "Barbados" },
    { flag: "🇧🇾", value: "+375", label: "Belarus" },
    { flag: "🇧🇪", value: "+32", label: "Belgium" },
    { flag: "🇧🇿", value: "+501", label: "Belize" },
    { flag: "🇧🇯", value: "+229", label: "Benin" },
    { flag: "🇧🇲", value: "+1-441", label: "Bermuda" },
    { flag: "🇧🇹", value: "+975", label: "Bhutan" },
    { flag: "🇧🇴", value: "+591", label: "Bolivia" },
    { flag: "🇧🇦", value: "+387", label: "Bosnia and Herzegovina" },
    { flag: "🇧🇼", value: "+267", label: "Botswana" },
    { flag: "🇧🇷", value: "+55", label: "Brazil" },
    { flag: "🇮🇴", value: "+246", label: "British Indian Ocean Territory" },
    { flag: "🇻🇬", value: "+1-284", label: "British Virgin Islands" },
    { flag: "🇧🇳", value: "+673", label: "Brunei" },
    { flag: "🇧🇬", value: "+359", label: "Bulgaria" },
    { flag: "🇧🇫", value: "+226", label: "Burkina Faso" },
    { flag: "🇧🇮", value: "+257", label: "Burundi" },
    { flag: "🇨🇻", value: "+238", label: "Cabo Verde" },
    { flag: "🇰🇭", value: "+855", label: "Cambodia" },
    { flag: "🇨🇲", value: "+237", label: "Cameroon" },
    { flag: "🇨🇦", value: "+1", label: "Canada" },
    { flag: "🇰🇾", value: "+1-345", label: "Cayman Islands" },
    { flag: "🇨🇫", value: "+236", label: "Central African Republic" },
    { flag: "🇹🇩", value: "+235", label: "Chad" },
    { flag: "🇨🇱", value: "+56", label: "Chile" },
    { flag: "🇨🇳", value: "+86", label: "China" },
    { flag: "🇨🇽", value: "+61", label: "Christmas Island" },
    { flag: "🇨🇨", value: "+61", label: "Cocos (Keeling) Islands" },
    { flag: "🇨🇴", value: "+57", label: "Colombia" },
    { flag: "🇰🇲", value: "+269", label: "Comoros" },
    { flag: "🇨🇬", value: "+242", label: "Republic of the Congo" },
    { flag: "🇨🇩", value: "+243", label: "Democratic Republic of the Congo" },
    { flag: "🇨🇰", value: "+682", label: "Cook Islands" },
    { flag: "🇨🇷", value: "+506", label: "Costa Rica" },
    { flag: "🇨🇮", value: "+225", label: "Côte d'Ivoire" },
    { flag: "🇭🇷", value: "+385", label: "Croatia" },
    { flag: "🇨🇺", value: "+53", label: "Cuba" },
    { flag: "🇨🇾", value: "+357", label: "Cyprus" },
    { flag: "🇨🇿", value: "+420", label: "Czech Republic" },
    { flag: "🇩🇰", value: "+45", label: "Denmark" },
    { flag: "🇩🇯", value: "+253", label: "Djibouti" },
    { flag: "🇩🇲", value: "+1-767", label: "Dominica" },
    { flag: "🇩🇴", value: "+1-809", label: "Dominican Republic" },
    { flag: "🇪🇨", value: "+593", label: "Ecuador" },
    { flag: "🇪🇬", value: "+20", label: "Egypt" },
    { flag: "🇸🇻", value: "+503", label: "El Salvador" },
    { flag: "🇬🇶", value: "+240", label: "Equatorial Guinea" },
    { flag: "🇪🇷", value: "+291", label: "Eritrea" },
    { flag: "🇪🇪", value: "+372", label: "Estonia" },
    { flag: "🇪🇹", value: "+251", label: "Ethiopia" },
    { flag: "🇫🇰", value: "+500", label: "Falkland Islands" },
    { flag: "🇫🇴", value: "+298", label: "Faroe Islands" },
    { flag: "🇫🇯", value: "+679", label: "Fiji" },
    { flag: "🇫🇮", value: "+358", label: "Finland" },
    { flag: "🇫🇷", value: "+33", label: "France" },
    { flag: "🇬🇫", value: "+594", label: "French Guiana" },
    { flag: "🇵🇫", value: "+689", label: "French Polynesia" },
    { flag: "🇹🇫", value: "+262", label: "French Southern Territories" },
    { flag: "🇬🇦", value: "+241", label: "Gabon" },
    { flag: "🇬🇲", value: "+220", label: "Gambia" },
    { flag: "🇬🇪", value: "+995", label: "Georgia" },
    { flag: "🇩🇪", value: "+49", label: "Germany" },
    { flag: "🇬🇭", value: "+233", label: "Ghana" },
    { flag: "🇬🇮", value: "+350", label: "Gibraltar" },
    { flag: "🇬🇷", value: "+30", label: "Greece" },
    { flag: "🇬🇱", value: "+299", label: "Greenland" },
    { flag: "🇬🇩", value: "+1-473", label: "Grenada" },
    { flag: "🇬🇵", value: "+590", label: "Guadeloupe" },
    { flag: "🇬🇺", value: "+1-671", label: "Guam" },
    { flag: "🇬🇹", value: "+502", label: "Guatemala" },
    { flag: "🇬🇬", value: "+44", label: "Guernsey" },
    { flag: "🇬🇳", value: "+224", label: "Guinea" },
    { flag: "🇬🇼", value: "+245", label: "Guinea-Bissau" },
    { flag: "🇬🇾", value: "+592", label: "Guyana" },
    { flag: "🇭🇹", value: "+509", label: "Haiti" },
    { flag: "🇭🇳", value: "+504", label: "Honduras" },
    { flag: "🇭🇰", value: "+852", label: "Hong Kong" },
    { flag: "🇭🇺", value: "+36", label: "Hungary" },
    { flag: "🇮🇸", value: "+354", label: "Iceland" },
    { flag: "🇮🇳", value: "+91", label: "India" },
    { flag: "🇮🇩", value: "+62", label: "Indonesia" },
    { flag: "🇮🇷", value: "+98", label: "Iran" },
    { flag: "🇮🇶", value: "+964", label: "Iraq" },
    { flag: "🇮🇪", value: "+353", label: "Ireland" },
    { flag: "🇮🇲", value: "+44", label: "Isle of Man" },
    { flag: "🇮🇱", value: "+972", label: "Israel" },
    { flag: "🇮🇹", value: "+39", label: "Italy" },
    { flag: "🇯🇲", value: "+1-876", label: "Jamaica" },
    { flag: "🇯🇵", value: "+81", label: "Japan" },
    { flag: "🇯🇪", value: "+44", label: "Jersey" },
    { flag: "🇯🇴", value: "+962", label: "Jordan" },
    { flag: "🇰🇿", value: "+7", label: "Kazakhstan" },
    { flag: "🇰🇪", value: "+254", label: "Kenya" },
    { flag: "🇰🇮", value: "+686", label: "Kiribati" },
    { flag: "🇽🇰", value: "+383", label: "Kosovo" },
    { flag: "🇰🇼", value: "+965", label: "Kuwait" },
    { flag: "🇰🇬", value: "+996", label: "Kyrgyzstan" },
    { flag: "🇱🇦", value: "+856", label: "Laos" },
    { flag: "🇱🇻", value: "+371", label: "Latvia" },
    { flag: "🇱🇧", value: "+961", label: "Lebanon" },
    { flag: "🇱🇸", value: "+266", label: "Lesotho" },
    { flag: "🇱🇷", value: "+231", label: "Liberia" },
    { flag: "🇱🇾", value: "+218", label: "Libya" },
    { flag: "🇱🇮", value: "+423", label: "Liechtenstein" },
    { flag: "🇱🇹", value: "+370", label: "Lithuania" },
    { flag: "🇱🇺", value: "+352", label: "Luxembourg" },
    { flag: "🇲🇴", value: "+853", label: "Macao" },
    { flag: "🇲🇰", value: "+389", label: "North Macedonia" },
    { flag: "🇲🇬", value: "+261", label: "Madagascar" },
    { flag: "🇲🇼", value: "+265", label: "Malawi" },
    { flag: "🇲🇾", value: "+60", label: "Malaysia" },
    { flag: "🇲🇻", value: "+960", label: "Maldives" },
    { flag: "🇲🇱", value: "+223", label: "Mali" },
    { flag: "🇲🇹", value: "+356", label: "Malta" },
    { flag: "🇲🇭", value: "+692", label: "Marshall Islands" },
    { flag: "🇲🇶", value: "+596", label: "Martinique" },
    { flag: "🇲🇷", value: "+222", label: "Mauritania" },
    { flag: "🇲🇺", value: "+230", label: "Mauritius" },
    { flag: "🇾🇹", value: "+262", label: "Mayotte" },
    { flag: "🇲🇽", value: "+52", label: "Mexico" },
    { flag: "🇫🇲", value: "+691", label: "Micronesia" },
    { flag: "🇲🇩", value: "+373", label: "Moldova" },
    { flag: "🇲🇨", value: "+377", label: "Monaco" },
    { flag: "🇲🇳", value: "+976", label: "Mongolia" },
    { flag: "🇲🇪", value: "+382", label: "Montenegro" },
    { flag: "🇲🇸", value: "+1-664", label: "Montserrat" },
    { flag: "🇲🇦", value: "+212", label: "Morocco" },
    { flag: "🇲🇿", value: "+258", label: "Mozambique" },
    { flag: "🇲🇲", value: "+95", label: "Myanmar" },
    { flag: "🇳🇦", value: "+264", label: "Namibia" },
    { flag: "🇳🇷", value: "+674", label: "Nauru" },
    { flag: "🇳🇵", value: "+977", label: "Nepal" },
    { flag: "🇳🇱", value: "+31", label: "Netherlands" },
    { flag: "🇳🇨", value: "+687", label: "New Caledonia" },
    { flag: "🇳🇿", value: "+64", label: "New Zealand" },
    { flag: "🇳🇮", value: "+505", label: "Nicaragua" },
    { flag: "🇳🇪", value: "+227", label: "Niger" },
    { flag: "🇳🇬", value: "+234", label: "Nigeria" },
    { flag: "🇳🇺", value: "+683", label: "Niue" },
    { flag: "🇳🇫", value: "+672", label: "Norfolk Island" },
    { flag: "🇰🇵", value: "+850", label: "North Korea" },
    { flag: "🇲🇵", value: "+1-670", label: "Northern Mariana Islands" },
    { flag: "🇳🇴", value: "+47", label: "Norway" },
    { flag: "🇴🇲", value: "+968", label: "Oman" },
    { flag: "🇵🇰", value: "+92", label: "Pakistan" },
    { flag: "🇵🇼", value: "+680", label: "Palau" },
    { flag: "🇵🇸", value: "+970", label: "Palestine" },
    { flag: "🇵🇦", value: "+507", label: "Panama" },
    { flag: "🇵🇬", value: "+675", label: "Papua New Guinea" },
    { flag: "🇵🇾", value: "+595", label: "Paraguay" },
    { flag: "🇵🇪", value: "+51", label: "Peru" },
    { flag: "🇵🇭", value: "+63", label: "Philippines" },
    { flag: "🇵🇳", value: "+64", label: "Pitcairn Islands" },
    { flag: "🇵🇱", value: "+48", label: "Poland" },
    { flag: "🇵🇹", value: "+351", label: "Portugal" },
    { flag: "🇵🇷", value: "+1-787", label: "Puerto Rico" },
    { flag: "🇶🇦", value: "+974", label: "Qatar" },
    { flag: "🇷🇪", value: "+262", label: "Réunion" },
    { flag: "🇷🇴", value: "+40", label: "Romania" },
    { flag: "🇷🇺", value: "+7", label: "Russia" },
    { flag: "🇷🇼", value: "+250", label: "Rwanda" },
    { flag: "🇧🇱", value: "+590", label: "Saint Barthélemy" },
    { flag: "🇸🇭", value: "+290", label: "Saint Helena" },
    { flag: "🇰🇳", value: "+1-869", label: "Saint Kitts and Nevis" },
    { flag: "🇱🇨", value: "+1-758", label: "Saint Lucia" },
    { flag: "🇲🇫", value: "+590", label: "Saint Martin" },
    { flag: "🇵🇲", value: "+508", label: "Saint Pierre and Miquelon" },
    { flag: "🇻🇨", value: "+1-784", label: "Saint Vincent and the Grenadines" },
    { flag: "🇼🇸", value: "+685", label: "Samoa" },
    { flag: "🇸🇲", value: "+378", label: "San Marino" },
    { flag: "🇸🇹", value: "+239", label: "Sao Tome and Principe" },
    { flag: "🇸🇦", value: "+966", label: "Saudi Arabia" },
    { flag: "🇸🇳", value: "+221", label: "Senegal" },
    { flag: "🇷🇸", value: "+381", label: "Serbia" },
    { flag: "🇸🇨", value: "+248", label: "Seychelles" },
    { flag: "🇸🇱", value: "+232", label: "Sierra Leone" },
    { flag: "🇸🇬", value: "+65", label: "Singapore" },
    { flag: "🇸🇽", value: "+1-721", label: "Sint Maarten" },
    { flag: "🇸🇰", value: "+421", label: "Slovakia" },
    { flag: "🇸🇮", value: "+386", label: "Slovenia" },
    { flag: "🇸🇧", value: "+677", label: "Solomon Islands" },
    { flag: "🇸🇴", value: "+252", label: "Somalia" },
    { flag: "🇿🇦", value: "+27", label: "South Africa" },
    { flag: "🇬🇸", value: "+500", label: "South Georgia" },
    { flag: "🇸🇸", value: "+211", label: "South Sudan" },
    { flag: "🇪🇸", value: "+34", label: "Spain" },
    { flag: "🇱🇰", value: "+94", label: "Sri Lanka" },
    { flag: "🇸🇩", value: "+249", label: "Sudan" },
    { flag: "🇸🇷", value: "+597", label: "Suriname" },
    { flag: "🇸🇯", value: "+47", label: "Svalbard and Jan Mayen" },
    { flag: "🇸🇪", value: "+46", label: "Sweden" },
    { flag: "🇨🇭", value: "+41", label: "Switzerland" },
    { flag: "🇸🇾", value: "+963", label: "Syria" },
    { flag: "🇹🇼", value: "+886", label: "Taiwan" },
    { flag: "🇹🇯", value: "+992", label: "Tajikistan" },
    { flag: "🇹🇿", value: "+255", label: "Tanzania" },
    { flag: "🇹🇭", value: "+66", label: "Thailand" },
    { flag: "🇹🇱", value: "+670", label: "Timor-Leste" },
    { flag: "🇹🇬", value: "+228", label: "Togo" },
    { flag: "🇹🇰", value: "+690", label: "Tokelau" },
    { flag: "🇹🇴", value: "+676", label: "Tonga" },
    { flag: "🇹🇹", value: "+1-868", label: "Trinidad and Tobago" },
    { flag: "🇹🇳", value: "+216", label: "Tunisia" },
    { flag: "🇹🇷", value: "+90", label: "Turkey" },
    { flag: "🇹🇲", value: "+993", label: "Turkmenistan" },
    { flag: "🇹🇨", value: "+1-649", label: "Turks and Caicos Islands" },
    { flag: "🇹🇻", value: "+688", label: "Tuvalu" },
    { flag: "🇺🇬", value: "+256", label: "Uganda" },
    { flag: "🇺🇦", value: "+380", label: "Ukraine" },
    { flag: "🇦🇪", value: "+971", label: "United Arab Emirates" },
    { flag: "🇬🇧", value: "+44", label: "United Kingdom" },
    { flag: "🇺🇲", value: "+1", label: "U.S. Minor Outlying Islands" },
    { flag: "🇺🇸", value: "+1", label: "United States" },
    { flag: "🇺🇾", value: "+598", label: "Uruguay" },
    { flag: "🇺🇿", value: "+998", label: "Uzbekistan" },
    { flag: "🇻🇺", value: "+678", label: "Vanuatu" },
    { flag: "🇻🇦", value: "+379", label: "Vatican City" },
    { flag: "🇻🇪", value: "+58", label: "Venezuela" },
    { flag: "🇻🇳", value: "+84", label: "Vietnam" },
    { flag: "🇼🇫", value: "+681", label: "Wallis and Futuna" },
    { flag: "🇪🇭", value: "+212", label: "Western Sahara" },
    { flag: "🇾🇪", value: "+967", label: "Yemen" },
    { flag: "🇿🇲", value: "+260", label: "Zambia" },
    { flag: "🇿🇼", value: "+263", label: "Zimbabwe" },
];

export default COUNTRY_PHONE_CODES;
